name: 'Destroy'

on:
  workflow_dispatch:
permissions: write-all
jobs:
  terraform:
    name: 'Run Terraform'
    env:
      ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
    environment: Azure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.3

      - name: login
        uses: Azure/login@v1.5.0
        with:
          client-id: ${{ vars.ARM_CLIENT_ID }}
          tenant-id: ${{ vars.ARM_TENANT_ID }}
          subscription-id: ${{ vars.ARM_SUBSCRIPTION_ID }}

      - name: Terraform Init
        env:
          ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
        run: terraform init -backend-config="config/backend.conf"

      - name: Whitelist GitHub Runner IP
        run: |
            agentIP=$(curl -s https://api.ipify.org/)
            az keyvault network-rule add --name pick2acrdemo --ip-address $agentIP
            sleep 60 

      - name: Terraform Destroy
        env:
          TF_VAR_client_id: ${{ vars.ARM_CLIENT_ID }}
          TF_VAR_subscription_id: ${{ vars.ARM_SUBSCRIPTION_ID }}
          TF_VAR_tenant_id: ${{ vars.ARM_TENANT_ID }}
          TF_VAR_local_ip: ${{ vars.LOCAL_IP }}
        run: terraform destroy -auto-approve 

